backend:
  name: git-gateway
  branch: develop

media_folder: static/img
public_folder: /img

collections:
  - name: 'work-item'
    label: 'Work'
    folder: 'src/content/work'
    create: true
    slug: '{{slug}}'
    fields:
      - {
          label: 'Template Key',
          name: 'templateKey',
          widget: 'hidden',
          default: 'work-item',
        }
      - { label: 'Title', name: 'title', widget: 'string' }
      - { label: 'Short Description', name: 'shortDescription', widget: 'text' }
      - { label: 'Featured Image', name: 'featuredImage', widget: 'image' }
      - { label: 'Project Image', name: 'projectImage', widget: 'image' }
      - {
          label: 'Services List 1 Title',
          name: 'servicesList1Title',
          widget: 'string',
          required: false,
        }
      - {
          label: 'services List 1',
          name: 'servicesList1',
          widget: 'list',
          required: false,
        }
      - {
          label: 'Services List 2 Title',
          name: 'servicesList2Title',
          widget: 'string',
          required: false,
        }
      - {
          label: 'Services List 2',
          name: 'servicesList2',
          widget: 'list',
          required: false,
        }
      - {
          label: 'Services List 3 Title',
          name: 'servicesList3Title',
          widget: 'string',
          required: false,
        }
      - {
          label: 'Services List 3',
          name: 'servicesList3',
          widget: 'list',
          required: false,
        }
      - {
          lable: 'Link Text',
          name: 'linkText',
          widget: 'string',
          required: false,
        }
      - {
          lable: 'Link URL',
          name: 'linkUrl',
          widget: 'string',
          required: false,
        }
      - { label: 'Tags', name: 'tags', widget: 'list' }
      - {
          label: 'Class Name',
          name: 'className',
          widget: 'string',
          required: false,
        }
      - { label: 'Body', name: 'body', widget: 'markdown' }
  - name: 'work-section'
    label: 'Work Section'
    folder: 'src/content/work-sections'
    create: true
    slug: '{{slug}}'
    fields:
      - { label: 'Title', name: 'title', widget: 'string' }
      - {
          label: 'Work Relation',
          name: 'relatedWorkItem',
          widget: 'relation',
          collection: 'work-item',
          searchFields: ['title'],
          valueField: 'title',
          displayFields: ['title', 'shortDescription'],
        }
      - {
          label: 'Class Name',
          name: 'className',
          widget: 'string',
          required: false,
        }
      - { label: 'Sort Order', name: 'sortOrder', widget: 'number', default: 0 }
      - { label: 'Body', name: 'body', widget: 'markdown' }
